project 'TestImage.xcodeproj'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'TestImage' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  inhibit_all_warnings!

  # Pods for TestImage
  pod 'AFNetworking', '~> 3.2.1'

end
